spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:juntos
    username: sa
    password: 
  h2:
    console:
      enabled: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
